# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-18 03:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('inventory_id', models.CharField(max_length=32)),
                ('finished', models.BooleanField(default=True)),
                ('height', models.CharField(max_length=20)),
                ('width', models.CharField(max_length=20)),
                ('depth', models.CharField(max_length=20)),
                ('mass', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ArtworkView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Artwork')),
            ],
        ),
        migrations.CreateModel(
            name='UserCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='categories',
            field=models.ManyToManyField(to='web.UserCategories'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='media',
            field=models.ManyToManyField(to='web.UserMedia'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
